language: php

services:
  - mysql
  - memcached
  - redis

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then pecl install mailparse; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then pecl install mailparse-2.1.6; fi
  - echo 'upload_tmp_dir = "/tmp"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - cd tests/
  - composer install
  - vendor/bin/phpunit -c phpunit.cerb.platform.xml
